task: train
exp_dir: ./exp/o2_20k/ad_cnn_45conds/
data_dirs: [./dataset_deepmimo_road/o2_cond6/,./dataset_deepmimo_road/o2_cond26/,./dataset_deepmimo_road/o2_cond46/,./dataset_deepmimo_road/o2_cond66/,./dataset_deepmimo_road/o2_cond86/,./dataset_deepmimo_road/o2_cond106/,./dataset_deepmimo_road/o2_cond146/,./dataset_deepmimo_road/o2_cond166/,./dataset_deepmimo_road/o2_cond186/,./dataset_deepmimo_road/o2_cond206/,./dataset_deepmimo_road/o2_cond246/,./dataset_deepmimo_road/o2_cond266/,./dataset_deepmimo_road/o2_cond286/,./dataset_deepmimo_road/o2_cond306/,./dataset_deepmimo_road/o2_cond326/,./dataset_deepmimo_road/o2_cond346/,./dataset_deepmimo_road/o2_cond366/,./dataset_deepmimo_road/o2_cond386/,./dataset_deepmimo_road/o2_cond406/,./dataset_deepmimo_road/o2_cond426/,./dataset_deepmimo_road/o2_cond446/,./dataset_deepmimo_road/o2_cond466/,./dataset_deepmimo_road/o2_cond486/,./dataset_deepmimo_road/o2_cond506/,./dataset_deepmimo_road/o2_cond546/,./dataset_deepmimo_road/o2_cond566/,./dataset_deepmimo_road/o2_cond586/,./dataset_deepmimo_road/o2_cond606/,./dataset_deepmimo_road/o2_cond626/,./dataset_deepmimo_road/o2_cond646/,./dataset_deepmimo_road/o2_cond666/,./dataset_deepmimo_road/o2_cond686/,./dataset_deepmimo_road/o2_cond706/,./dataset_deepmimo_road/o2_cond746/,./dataset_deepmimo_road/o2_cond766/,./dataset_deepmimo_road/o2_cond786/,./dataset_deepmimo_road/o2_cond806/,./dataset_deepmimo_road/o2_cond846/,./dataset_deepmimo_road/o2_cond866/,./dataset_deepmimo_road/o2_cond886/,./dataset_deepmimo_road/o2_cond906/,./dataset_deepmimo_road/o2_cond926/,./dataset_deepmimo_road/o2_cond946/,./dataset_deepmimo_road/o2_cond966/,./dataset_deepmimo_road/o2_cond986/]
scheme: ad_cnn
iclloc_scheme: ~

num_ant: 32
num_car: 32
max_len_nei: 64
select: ~
radius: ~
inv_std: 100000
num_train_data: 20000
num_test_data: 20000

res_mlp:
  hidden_dim: 256
  num_blocks: 2
cnn:
  hidden_size: 32
mfc_net:
  hidden_size: 128
  num_layers: 2
alloc:
  embed_dim: 256
  num_heads: 4
  hidden_dim: 256
  depth: 8
iclloc:
  embed_dim: 256
  num_heads: 4
  hidden_dim: 512
  depth: 8

tensorboard_writer: True
num_epochs: 100000
num_max_steps: 300000
init_lr: 0.001
lr_decay_steps: [150000,200000,250000]
lr_decay_factor: 0.2
batch_size: 500
mix_train_datasets: True
gen_seq_datasets: True
len_nei_total: 64
len_nei_least: 16
len_nei_test: 64

log_step_inter: 100
save_epoch_inter: 100
test_epoch_inter: 20

finetune: False
finetune_model:
  exp_dir: ~
  epoch: ~